version: '3'
networks:
    proxy:
        external: true
services:
    db:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: admin
            MARIADB_DATABASE: go
            MARIADB_USER: socket
            MARIADB_PASSWORD: socketpw
    socket:
        image: cjpalmer/go-socket:1.0.0
    web:
        image: cjpalmer/go-web:1.0.0
        environment:
        - NGINX_HOST=purplebirdman.com
        - NGINX_PORT=80
        networks:
        - default
        - proxy
