version: '3'
services:
    db:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: admin
            MARIADB_DATABASE: go
            MARIADB_USER: socket
            MARIADB_PASSWORD: socketpw
    httpd:
        image: httpd:2.4
        volumes:
        - ./htdocs:/usr/local/apache2/htdocs
        - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
        - 8000:80
