version: '3'
networks:
    go-backend:
        driver: bridge
services:
    db:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: admin
            MARIADB_DATABASE: go
            MARIADB_USER: socket
            MARIADB_PASSWORD: socketpw
        networks:
        - go-backend
    socket:
        build: ./socket
        image: cjpalmer/go-socket:1.0.0
        networks:
        - default
        - go-backend
    web:
        build: ./web
        image: cjpalmer/go-web:1.0.0
        environment:
        - NGINX_HOST=purplebirdman.com
        - NGINX_PORT=80
        ports:
        - 80:80
