version: '3'
networks:
    default:
        external:
            name: proxy
services:
    db:
        image: mariadb:10.6
        environment:
            MARIADB_ROOT_PASSWORD: admin
            MARIADB_DATABASE: go
            MARIADB_USER: socket
            MARIADB_PASSWORD: socketpw
    socket:
        build: ./socket
        image: cliftonpalmer/go-socket
    httpd:
        image: httpd:2.4
        volumes:
        - ./htdocs:/usr/local/apache2/htdocs
