version: '3'
services:
    db:
        image: postgres:13.4-alpine
        environment:
            POSTGRES_USER: go
            POSTGRES_PASSWORD: socketpw
        ports:
        - 5432:5432
    httpd:
        build: .
        image: httpdlua
        volumes:
        - ./htdocs:/usr/local/apache2/htdocs
        - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
        - 8000:80
